### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jiancanxuepiao** [r3vn/badKarma#3]
Traceback (most recent call last):
  File "badkarma.py", line 39, in <module>
    Handler(database)
  File "/root/jcxp/scan/badKarma/core/main.py", line 59, in __init__
    self.extensions  = Extensions() # extension engine
  File "/root/jcxp/scan/badKarma/core/extensions.py", line 11, in __init__
    self._indicize_modules()
  File "/root/jcxp/scan/badKarma/core/extensions.py", line 59, in _indicize_modules
    module = importlib.import_module('extensions.'+module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/jcxp/scan/badKarma/extensions/bruter.py", line 26, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available

root@kali:~/jcxp/scan/badKarma# apt-cache rdepends gir1.2-vte-2.91
gir1.2-vte-2.91
Reverse Depends:
  guake
  reportbug
  virt-manager
  terminator
  sugar-terminal-activity
  sugar-pippy-activity
  reportbug-gtk
  python-faraday
  pycode-browser
  lios
  libvte-2.91-dev
  laditools
  king-phisher
  gnome-builder
  education-desktop-other
  gedit-plugin-terminal
  gdebi

**Comment by r3vn** [comment]
b241a80 should fix this, can you confirm?
