### ISSUE TITLE
Open older version of session file

### ISSUE THREAD

**Issue by re8el** [r3vn/badKarma#8]
Hi,

i have updated badkarma but now older session files i just cannot open, something is breaks.

this only happens with older version of session files. The new ones opens ok using the comand ./badkarma.py --session .....

#####
(badkarma.py:16228): Gtk-WARNING **: 16:46:40.092: gtk_window_set_titlebar() called on a realized window
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: activity_log.target

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./badkarma.py", line 39, in <module>
    Handler(database)
  File "/opt/badKarma/core/main.py", line 93, in __init__
    self.logger = Logger(self.database)
  File "/opt/badKarma/core/workspace.py", line 72, in __init__
    self.refresh(self.database)
  File "/opt/badKarma/core/workspace.py", line 100, in refresh
    logs = self.database.get_logs()
  File "/opt/badKarma/core/database.py", line 183, in get_logs
    return self.session.query(activity_log).all()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2783, in all
    return list(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2935, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2958, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: activity_log.target [SQL: 'SELECT activity_log.id AS activity_log_id, activity_log.pid AS activity_log_pid, activity_log.start_time AS activity_log_start_time, activity_log.end_time AS activity_log_end_time, activity_log.title AS activity_log_title, activity_log.output AS activity_log_output, activity_log.extension AS activity_log_extension, activity_log.target AS activity_log_target \nFROM activity_log'] (Background on this error at: http://sqlalche.me/e/e3q8)

[3]  + 16228 exit 1     ./badkarma.py --session

**Comment by r3vn** [comment]
Hi, 
this is a known issue since database structure changed from the first release.

G.

**Comment by re8el** [comment]
Hi,

at the date of this my 1st post, i had updated badkarma and open this issue. after that i had created new session files and all worked perfect from that point on. Until today after a new pull from git.

Again i cannot open the session files ii have created after the last update.

What this means is that already created sessions file cannot be opened after a git pull. His this correct?



### ERROR##
(badkarma.py:106591): Gtk-WARNING **: 14:29:06.021: gtk_window_set_titlebar() called on a realized window
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: targets.scope

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./badkarma.py", line 39, in <module>
    Handler(database)
  File "/opt/badKarma/core/main.py", line 98, in __init__
    self.host_list     = Hostlist(self.database)
  File "/opt/badKarma/core/workspace.py", line 468, in __init__
    self.refresh(self.database)
  File "/opt/badKarma/core/workspace.py", line 474, in refresh
    hosts = self.database.get_hosts()
  File "/opt/badKarma/core/database.py", line 171, in get_hosts
    return self.session.query(targets).all()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2783, in all
    return list(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2935, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2958, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 508, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: targets.scope [SQL: 'SELECT targets.id AS targets_id, targets.address AS targets_address, targets.os_match AS targets_os_match, targets.os_accuracy AS targets_os_accuracy, targets.ipv4 AS targets_ipv4, targets.ipv6 AS targets_ipv6, targets.mac AS targets_mac, targets.status AS targets_status, targets.tcpsequence AS targets_tcpsequence, targets.hostname AS targets_hostname, targets.vendor AS targets_vendor, targets.uptime AS targets_uptime, targets.lastboot AS targets_lastboot, targets.distance AS targets_distance, targets.latitude AS targets_latitude, targets.longitude AS targets_longitude, targets.scripts AS targets_scripts, targets.scope AS targets_scope, targets.country_code AS targets_country_code, targets.country_name AS targets_country_name, targets.isp AS targets_isp, targets.organization AS targets_organization \nFROM targets'] (Background on this error at: http://sqlalche.me/e/e3q8)

[1]  + 106591 exit 1     ./badkarma.py --session /root/badksessions/tm0.sqlite

**Comment by r3vn** [comment]
> What this means is that already created sessions file cannot be opened after a git pull. His this correct?

this is partially correct, session files broke after a "core/database.py" update, since this is the development branch of badKarma, database changes are frequent.
You can always try to manually edit the sqllite file matching the new DB structure.

Anyway a stable version is planned to be released by the end of the year. 

G.
